### PR TITLE
Added license

### PR DESCRIPTION
**Pull request by esslamben**

### CODE REVIEW

**Comment by esslamben** [comment]
Had to remake the branch, for some reason the squash was causing me a lot of trouble. I went ahead and deleted the old branch. This version should be correct. Let me know if you need anything else changing.

**Comment by DipanshKhandelwal** [comment]
Please look at this once for correct format [MIT LICENSE](https://opensource.org/licenses/MIT) or maybe refer [here](https://github.com/DipanshKhandelwal/PythonScripts/blob/master/LICENSE).

**Comment by esslamben** [comment]
Oh wow sorry mate, I'm an idiot. Had auto-formatting on. This should be fine now, I also squashed the commit(which worked first time now for some reason 😄 )

**Review by DipanshKhandelwal — APPROVED** [review]
Cool :joy: :metal:

**Pull request merged**
